### ISSUE TITLE
Version 1.8.0 support

### ISSUE THREAD

**Issue by Teyras** [alxlit/coffeescript-php#24]
Is there any chance for this tool to support newer versions of coffeescript? The function chaining syntax has changed since 1.7.0, for example this:

```coffeescript
$ '<div>'
    .appendTo foo
```
used to mean `$('<div>'.appendTo(foo))`, but since 1.7.0 it means `$('<div>').appendTo(foo)`

**Comment by alxlit** [comment]
It's very unlikely, sorry
